server:
  port: 8001
eureka:
  instance:
    prefer-ip-address: true
  #    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      serviceUrl: http://localhost:8761/eureka/
spring:
  application:
    name: IO-SERVICE
